# Generated by Django 4.0.7 on 2023-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'تحویل'), ('unpaid', 'پرداخت نشده'), ('returned', 'بازگشت داده شد'), ('sending', 'درحال ارسال'), ('failed', 'ناموفق')], default='unpaid', max_length=15, verbose_name='وضعیت'),
        ),
    ]
