# Generated by Django 3.2.5 on 2022-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type_category',
            field=models.CharField(choices=[('special_offer', 'پیشنهادات ویژه'), ('seasonal', 'فصلی')], max_length=15, verbose_name='نوع دسته بندی'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], default='d', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='section',
            field=models.CharField(choices=[('long_spec', 'توضیحات بلند'), ('short_spec', 'توضیحات کوتاه'), ('both', 'هردو')], max_length=20, verbose_name='بخش'),
        ),
    ]
