# Generated by Django 4.0.7 on 2023-06-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='ادرس دسته بندی')),
                ('status', models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='عکس')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('type_category', models.CharField(choices=[('seasonal', 'فصلی'), ('special_offer', 'پیشنهادات ویژه')], max_length=15, verbose_name='نوع دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ویژه',
                'verbose_name_plural': 'دسته بندی های ویژه',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='ادرس دسته بندی')),
                ('status', models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='عکس')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
