# Generated by Django 4.0.7 on 2023-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='type_category',
            field=models.CharField(choices=[('seasonal', 'فصلی'), ('special_offer', 'پیشنهادات ویژه')], max_length=15, verbose_name='نوع دسته بندی'),
        ),
    ]
