# Generated by Django 4.0.7 on 2023-06-04 08:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد رنگ')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='اعتبار از')),
                ('valid_to', models.DateTimeField(verbose_name='اعتبار تا')),
                ('active', models.BooleanField(verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تخفیف محصول',
                'verbose_name_plural': 'تخفیف محصولات',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='ادرس محصول')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='معرفی محصول')),
                ('price', models.FloatField(verbose_name='قیمت واقعی محصول')),
                ('thumbnail', models.ImageField(upload_to='image', verbose_name='عکس')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateField(auto_now=True, verbose_name='زمان تغییر')),
                ('status', models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], default='d', max_length=1, verbose_name='وضعیت')),
                ('quantity', models.IntegerField(verbose_name='تعداد محصولات')),
                ('available', models.BooleanField(default=True, verbose_name='موجود بودن محصول')),
                ('sales_number', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('banner', models.ManyToManyField(blank=True, related_name='products_for_banner', to='categories.banner', verbose_name='بنرها')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('discount_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.discountproduct', verbose_name='تخفیف محصول')),
                ('main_category', models.ManyToManyField(related_name='products_for_category', to='categories.category', verbose_name='دسته ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
                ('visits', models.ManyToManyField(blank=True, related_name='product', to='products.ipaddress', verbose_name='تعداد بازدید ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'اندازه',
                'verbose_name_plural': 'اندازه ها',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='ویژگی')),
                ('value', models.CharField(max_length=150, verbose_name='مقدار ویژگی')),
                ('section', models.CharField(choices=[('both', 'هردو'), ('long_spec', 'توضیحات بلند'), ('short_spec', 'توضیحات کوتاه')], max_length=20, verbose_name='بخش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='products.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='قیمت اندازه محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='اندازه محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image', verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس ها',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='قیمت رنگ محصول')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='رنگ محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
