# Generated by Django 4.0.7 on 2023-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], default='d', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='section',
            field=models.CharField(choices=[('long_spec', 'توضیحات بلند'), ('short_spec', 'توضیحات کوتاه'), ('both', 'هردو')], max_length=20, verbose_name='بخش'),
        ),
    ]
