# Generated by Django 4.0.7 on 2023-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_banner_type_category'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_products', to='categories.category', verbose_name='دسته ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ManyToManyField(blank=True, related_name='banner_products', to='categories.banner', verbose_name='بنرها'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='section',
            field=models.CharField(choices=[('short_spec', 'توضیحات کوتاه'), ('long_spec', 'توضیحات بلند'), ('both', 'هردو')], max_length=20, verbose_name='بخش'),
        ),
    ]
