# Generated by Django 4.0.7 on 2023-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_main_category_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='section',
            field=models.CharField(choices=[('short_spec', 'توضیحات کوتاه'), ('both', 'هردو'), ('long_spec', 'توضیحات بلند')], max_length=20, verbose_name='بخش'),
        ),
    ]
