# Generated by Django 3.2.5 on 2022-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('failed', 'ناموفق'), ('unpaid', 'پرداخت نشده'), ('sending', 'درحال ارسال'), ('delivered', 'تحویل'), ('returned', 'بازگشت داده شد')], default='unpaid', max_length=15, verbose_name='وضعیت'),
        ),
    ]
